### ISSUE TITLE
As a UX'er I need to Schedule users to interview in order to obtain the user feedback

### ISSUE THREAD

**Issue by jmheaster** [CivicActions/agile-california#27] opened 2016-05-20 19:28 UTC

**Comment by hpoole** [comment] 2016-05-24 16:57
I will take scheduling end user interviews for Friday 5/27 (Henry) at 10am Pacific.

**Comment by RobertLRead** [comment] 2016-05-24 18:38
Jason, in order to make this testable we need to put a specific date on it --- or is it already done?  I don't having a story that is open ended.

**Comment by elizabethraley** [comment] 2016-05-24 19:50
Duplicate of #16

**Closed as completed** 2016-05-24 19:50 UTC
